export const ROOM_KIND_LABELS = {
  entrance: "Entrance",
  elevator: "Elevator",
  waiting: "Waiting",
  emergency: "Emergency",
  rescue: "Rescue Bay",
  emergency_consult: "ER Consult",
  registration: "Registration",
  triage: "Triage",
  consultation: "Consultation",
  doctor_entry: "Doctor Entry",
  fever: "Fever Clinic",
  internal_medicine: "Internal Med",
  surgery: "Surgery",
  pediatrics: "Pediatrics",
  obgyn: "OB-GYN",
  outpatient: "Outpatient",
  pharmacy: "Pharmacy",
  pharmacy_pickup: "Pharmacy",
  lab: "Lab",
  icu: "ICU Beds",
  icu_station: "ICU Station",
  monitor: "Monitor",
  mdt: "MDT Center",
  mdt_meeting: "Conference",
  imaging_review: "Imaging Review",
  specialist: "Specialist",
  ward: "Ward Rooms",
  nurse_station: "Nurse Station",
  doctor_office: "Doctor Office",
};

export const DEPARTMENT_STATUS = {
  emergency: { status: "Ready", patients: 3, accent: "#d85e5e" },
  outpatient: { status: "Open", patients: 12, accent: "#4b79d8" },
  pharmacy: { status: "Dispensing", patients: 5, accent: "#87b96b" },
  lab: { status: "Testing", patients: 7, accent: "#55b8c8" },
  icu: { status: "Monitoring", patients: 4, accent: "#d46d8e" },
  mdt: { status: "Consulting", patients: 2, accent: "#9b87f5" },
  ward: { status: "Admitted", patients: 18, accent: "#66bfa2" },
};
